language: elixir

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.4.5
    - otp_release: 20.3
      elixir: 1.4.5

    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.3
      elixir: 1.5.3

    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6

    - otp_release: 21.3
      elixir: 1.7.4

    - otp_release: 21.3
      elixir: 1.8.1

sudo: false
notifications:
  recipients:
    - self@falood.me
before_script:
  - mix deps.get --only test
